name: Deploy Titanic Survival Predictor Flask App to Render

on:
  push:
    branches: [ "main", "Titanic-Survival-Predictor-App" ]
  pull_request:
    branches: [ "main", "Titanic-Survival-Predictor-App" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: ['3.9', '3.10', '3.11']
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Unit Tests
      run: |
        python -m unittest discover -s tests/unit -p '*_test.py'

  deploy-to-render:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}
        wait-for-success: true  # Seems to not be working
